### ISSUE TITLE
Переопределение методов - неудачный пример

### ISSUE THREAD

**Issue by jocelot** [BelyiZ/JavaCourses#11]
[Тема 9. Наследование и static. Перегрузка и переопределение методов. Переопределение методов](https://github.com/BelyiZ/JavaCourses/wiki/%D0%A2%D0%B5%D0%BC%D0%B0-9.-%D0%9D%D0%B0%D1%81%D0%BB%D0%B5%D0%B4%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5-%D0%B8-static#%D0%9F%D0%B5%D1%80%D0%B5%D0%BE%D0%BF%D1%80%D0%B5%D0%B4%D0%B5%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-%D0%BC%D0%B5%D1%82%D0%BE%D0%B4%D0%BE%D0%B2)

Вот этот пример на мой взгляд не показательный:
```java 
new Car().refueling(33);
> Топливный бак заправлен на [33] литров
        
new ElectricCar().refueling(33);
> Аккумулятор заряжен на 33%
```

Суть переопределения - это вызов метода наследника, когда информация о наследнике есть только в рантайме. Я бы предложил что-то типа такого:

```java

Automobile autmobile;

autmobile = new Car();
autmobile.refueling(33);
> Топливный бак заправлен на [33] литров
        
autmobile = new ElectricCar();
autmobile.refueling(33);
> Аккумулятор заряжен на 33%
```

**Comment by AlekseyBush** [comment]
исправил
