### ISSUE TITLE
Общая информация о Java - стилистика

### ISSUE THREAD

**Issue by jocelot** [BelyiZ/JavaCourses#12]
[Общая информация о Java](https://github.com/BelyiZ/JavaCourses/wiki/%D0%A2%D0%B5%D0%BC%D0%B0-1.-%D0%92%D0%B2%D0%B5%D0%B4%D0%B5%D0%BD%D0%B8%D0%B5-%D0%B2-Java)

Немного хромает стилистика. Технические подробности  перемешаны с общим описанием. Например, абзацы про память и про "Особенности языка" нужно перенести к концу описания. А все после "По данным компании Oracle..." лучше в самое начало.

**Comment by AlekseyBush** [comment]
Исправлено
