### ISSUE TITLE
Checkout GItHub репозитория - глава не в том месте или что-то не дописано

### ISSUE THREAD

**Issue by jocelot** [BelyiZ/JavaCourses#13]
[Тема 1. Введение в Java](https://github.com/BelyiZ/JavaCourses/wiki/%D0%A2%D0%B5%D0%BC%D0%B0-1.-%D0%92%D0%B2%D0%B5%D0%B4%D0%B5%D0%BD%D0%B8%D0%B5-%D0%B2-Java#Checkout-GItHub-%D1%80%D0%B5%D0%BF%D0%BE%D0%B7%D0%B8%D1%82%D0%BE%D1%80%D0%B8%D1%8F)

Глава "Checkout GItHub репозитория", наверное, должна быть под или после "Общая информация о системах контроля версий".
А то получается, что сначала даются какие-то команды, а потом объясняется к чему они вообще.

**Comment by AlekseyBush** [comment]
Исправлено
