### ISSUE TITLE
Общая информация о системах контроля версий - ошибки

### ISSUE THREAD

**Issue by jocelot** [BelyiZ/JavaCourses#14]
[Общая информация о системах контроля версий](https://github.com/BelyiZ/JavaCourses/wiki/%D0%A2%D0%B5%D0%BC%D0%B0-1.-%D0%92%D0%B2%D0%B5%D0%B4%D0%B5%D0%BD%D0%B8%D0%B5-%D0%B2-Java#%D0%9E%D0%B1%D1%89%D0%B0%D1%8F-%D0%B8%D0%BD%D1%84%D0%BE%D1%80%D0%BC%D0%B0%D1%86%D0%B8%D1%8F-%D0%BE-%D1%81%D0%B8%D1%81%D1%82%D0%B5%D0%BC%D0%B0%D1%85-%D0%BA%D0%BE%D0%BD%D1%82%D1%80%D0%BE%D0%BB%D1%8F-%D0%B2%D0%B5%D1%80%D1%81%D0%B8%D0%B9)

Первый абзац несвязно выглядит:
Система контроля версий является прежде всего инструментом. Итак, система контроля версий – это система, записывающая изменения в файл или набор файлов в течение времени и позволяющая вернуться позже к определенной версии.

И второй тоже:
 То есть существует возможность гибко управлять некоторым **набором файлом**, откатываться до определенных версий в случае необходимости. 

"Распределенная система контроля версий" в конце - видимо это должен быть заголовок, а отформатировано как выделение.

**Comment by AlekseyBush** [comment]
Исправлено - переписано полностью
