### ISSUE TITLE
Не бьется содержание

### ISSUE THREAD

**Issue by Feanon** [BelyiZ/JavaCourses#16]
Блок 0 тема 0 - 3 пункта https://github.com/BelyiZ/JavaCourses/wiki
При открытии темы в содержании 4 пункта https://github.com/BelyiZ/JavaCourses/wiki/%D0%A2%D0%B5%D0%BC%D0%B0-0.-%D0%92%D0%B2%D0%B5%D0%B4%D0%B5%D0%BD%D0%B8%D0%B5-%D0%B2-%D0%BA%D1%83%D1%80%D1%81

п.с. извините - я аналитик, поэтому буду такую ерунду находить...

**Comment by Feanon** [comment]
Как смотрю - так везде.
т.е. это все-таки фича?:)

**Comment by AlekseyBush** [comment]
Решено. Такой стиль
