### ISSUE TITLE
Разница между StringBuilder и StringBuffer в потокобезопасности.

### ISSUE THREAD

**Issue by alex-trubin** [BelyiZ/JavaCourses#6]
[Соединение строк](https://github.com/BelyiZ/JavaCourses/wiki/%D0%A2%D0%B5%D0%BC%D0%B0-5.-%D0%A0%D0%B0%D0%B1%D0%BE%D1%82%D0%B0-%D1%81%D0%BE-%D1%81%D1%82%D1%80%D0%BE%D0%BA%D0%B0%D0%BC%D0%B8#%D0%A1%D0%BE%D0%B5%D0%B4%D0%B8%D0%BD%D0%B5%D0%BD%D0%B8%D0%B5-%D1%81%D1%82%D1%80%D0%BE%D0%BA)

> Разница между StringBuilder и StringBuffer в потокобезопасности. Первый может использоваться в многопоточной среде, второй - нет.

Наоборот.
StringBuilder - This class provides an API compatible with StringBuffer, but with no guarantee of synchronization.
StringBuffer - A thread-safe, mutable sequence of characters.

**Comment by BelyiZ-R** [comment]
Да, опечатка. Спасибо!

**Comment by BelyiZ** [comment]
Done
