### ISSUE TITLE
Опечатки #2

### ISSUE THREAD

**Issue by alex-trubin** [BelyiZ/JavaCourses#8]
[Тема-7.-Класс-Object-и-его-методы](https://github.com/BelyiZ/JavaCourses/wiki/%D0%A2%D0%B5%D0%BC%D0%B0-7.-%D0%9A%D0%BB%D0%B0%D1%81%D1%81-Object-%D0%B8-%D0%B5%D0%B3%D0%BE-%D0%BC%D0%B5%D1%82%D0%BE%D0%B4%D1%8B)

> Метод clone() создан для клонировать объекта – то есть создания его копии/дубликата.

"создан для клонирования"

----

[Модификаторы доступа](https://github.com/BelyiZ/JavaCourses/wiki/%D0%A2%D0%B5%D0%BC%D0%B0-8.-%D0%98%D0%BD%D0%BA%D0%B0%D0%BF%D1%81%D1%83%D0%BB%D1%8F%D1%86%D0%B8%D1%8F#%D0%9C%D0%BE%D0%B4%D0%B8%D1%84%D0%B8%D0%BA%D0%B0%D1%82%D0%BE%D1%80%D1%8B-%D0%B4%D0%BE%D1%81%D1%82%D1%83%D0%BF%D0%B0)

> import java.lang.String;

IMHO, лишнее :)

----
[Тема-9.-Наследование-и-static](https://github.com/BelyiZ/JavaCourses/wiki/%D0%A2%D0%B5%D0%BC%D0%B0-9.-%D0%9D%D0%B0%D1%81%D0%BB%D0%B5%D0%B4%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5-%D0%B8-static)

> Этот код распечатает текст 123.

Съехала разметка.

----
> В данном случае член данных x класса Car есть видимым в пределах пакета.

В данном случае поле `x` класса Car доступно для других классов в пределах пакета.

----
> Класс может быть объявлен окончательным(final):

"Класс может быть объявлен финальным (final):"
потому как дальше используется именно этот термин
"вы не можете наследовать от финального класса."

----

Вызовем его в main:
```java
Counter.invokeCounter();
        Counter.invokeCounter();
        Counter.invokeCounter();
```

форматирование кода слегка непонятное. Или просто неаккуратное.
Встречается по всей главе.

> И получим вывод в консоль:
Текущее значение счётчика - 1 Текущее значение счётчика - 2 Текущее значение счётчика - 3

Предлагаю:

И получим вывод в консоль:
```
Текущее значение счётчика - 1
Текущее значение счётчика - 2
Текущее значение счётчика - 3
```

----
> Нельзя можете получить доступ к НЕ статическим членам класса, внутри статического контекста, как вариант, метода или блока.

Забористо!
"Из статического контекста (блока, метода) нельзя получить доступ к нестатическим членам класса."

**Comment by jocelot** [comment]
https://github.com/BelyiZ/JavaCourses/wiki/Тема-8.-Инкапсуляция

https://github.com/BelyiZ/JavaCourses/wiki/%D0%A2%D0%B5%D0%BC%D0%B0-8.-%D0%98%D0%BD%D0%BA%D0%B0%D0%BF%D1%81%D1%83%D0%BB%D1%8F%D1%86%D0%B8%D1%8F#:~:text=%D0%98%D0%B7%20%D0%B2%D1%81%D0%B5%D1%85%20%D0%BE%D1%81%D1%82%D0%B0%D0%BB%D1%8C%D0%BD%D1%8B%D1%85-,%D0%BC%D0%B5%D1%81%D1%82%D1%8C,-%D1%8D%D1%82%D0%BE%20%D1%81%D0%B4%D0%B5%D0%BB%D0%B0%D1%82%D1%8C%20%D0%BD%D0%B5

Опечатка ("Из всех остальных **мест** ... "

**Comment by AlekseyBush** [comment]
исправлено
